version: '3.4'

x-default: &default
  volumes:
    - .:/pong
  depends_on:
    - db
    - redis
  env_file:
    - .env

services:
  web:
    <<: *default
    build: .
  test:
    <<: *default
    image: pong_web
    command: bin/spring server
    environment:
      - RAILS_ENV=test
    depends_on:
      - web
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
