version: '3.4'

x-default: &default
  image: "${PROD_IMAGE}"
  restart: always
  depends_on:
    - db
    - redis
  env_file:
    - .env

services:
  db:
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pong
      - POSTGRES_DB=pong_production
  web:
    <<: *default
    command: sh -c "rm -f tmp/pids/server.pid && bin/rake assets:precompile && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
  worker:
    <<: *default
    command: rake resque:work
    environment:
      - QUEUE=*
      - RAILS_ENV=production
  scheduler:
    <<: *default
    command: rake resque:scheduler

volumes:
  pgdata:
